### ISSUE TITLE
Code uses gethostbyname() which is deprecated

### ISSUE THREAD

**Issue by lgbaldoni** [hhromic/libe131#11]
Packaging libe131 for openSUSE linux and this warning comes out:
```
The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```
[Here](https://udrepper.livejournal.com/16116.html)'s a better explanation on why.

**Comment by hhromic** [comment]
Apologies for the really late reply and thanks for bringing this up.
I now made a basic implementation in e8199d6.
