### ISSUE TITLE
No buffer space available error

### ISSUE THREAD

**Issue by HakanL** [hhromic/libe131#6]
I'm trying to use the library to join multiple sACN universes (61 to be exact). I open a socket (based on the test_server example) and then I call join_multicast multiple times. I can only call it 20 times, then I'm getting an error saying:

> No buffer space available

How can I join multiple universes (>20) successfully? Multiple sockets?

**Comment by HakanL** [comment]
Turns out there's a default OS max of 20, set with sysctl for this parameter: net.ipv4.igmp_max_memberships

**Comment by hhromic** [comment]
Hello, thanks for rising the issue and finding out it was not related to libe131.
I'm very curious about the amount of universes you are trying to handle and happy that libe131 seems to fit your needs for this.
If you have a big installation working using libe131, and you feel like shooting a video demo, I would be more than happy to reference it as a success story for libe131.
Cheers!
